[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true

[tools]
"aqua:FiloSottile/age" = "1.2.1"
"aqua:direnv/direnv" = "2.37.1"
"aqua:docker/compose" = "5.0.0"
"aqua:a8m/envsubst" = "1.4.3"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:helm/helm" = "4.0.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:derailed/k9s" = "0.50.16"
"aqua:kubernetes-sigs/kind" = "0.30.0"
"aqua:kubernetes/kubectl" = "1.33.4"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:nodejs/node" = "25.2.1"
"aqua:pnpm/pnpm" = "10.25.0"
"aqua:pre-commit/pre-commit" = "4.5.0"
"aqua:getsops/sops" = "3.11.0"
"aqua:budimanjojo/talhelper" = "3.0.41"
"aqua:go-task/task" = "3.45.5"
"aqua:hashicorp/terraform" = "1.14.1"
"aqua:terraform-docs/terraform-docs" = "0.20.0"
"aqua:terraform-linters/tflint" = "0.60.0"
"aqua:aquasecurity/trivy" = "0.68.1"
"aqua:astral-sh/uv" = "0.9.16"
"aqua:hashicorp/vault" = "1.21.1"
# "aqua:loft-sh/vcluster" = "0.25.0"
"aqua:mikefarah/yq" = "4.49.2"
