[settings]
experimental = true
idiomatic_version_file_enable_tools = ["python"]
python.uv_venv_auto = true

[tools]
"aqua:FiloSottile/age" = "1.3.1"
"aqua:direnv/direnv" = "2.37.1"
"aqua:docker/compose" = "5.0.2"
"aqua:a8m/envsubst" = "1.4.3"
"aqua:fluxcd/flux2" = "2.7.5"
"aqua:helm/helm" = "4.1.1"
"aqua:jqlang/jq" = "1.8.1"
"aqua:derailed/k9s" = "0.50.18"
"aqua:kubernetes-sigs/kind" = "0.31.0"
"aqua:kubernetes/kubectl" = "1.33.4"
"aqua:kubernetes-sigs/kustomize" = "5.7.1"
"aqua:nodejs/node" = "25.6.1"
"aqua:pnpm/pnpm" = "10.29.3"
"aqua:pre-commit/pre-commit" = "4.5.1"
"aqua:getsops/sops" = "3.11.0"
"aqua:budimanjojo/talhelper" = "3.1.4"
"aqua:go-task/task" = "3.48.0"
"aqua:hashicorp/terraform" = "1.14.5"
"aqua:terraform-docs/terraform-docs" = "0.21.0"
"aqua:terraform-linters/tflint" = "0.61.0"
"aqua:aquasecurity/trivy" = "0.69.1"
"aqua:astral-sh/uv" = "0.10.2"
"aqua:hashicorp/vault" = "1.21.3"
# "aqua:loft-sh/vcluster" = "0.25.0"
"aqua:mikefarah/yq" = "4.52.2"
